### ISSUE TITLE
StartGroup 

### ISSUE THREAD

**Issue by 89z** [paulmach/protoscan#2]
I see that StartGroup is not used:

https://github.com/paulmach/protoscan/blob/4e53c68754323057b4e82c9eec24db18e0a1cd6f/message.go#L19-L27

I think this is a problem, as some servers are still using it, for example `android.clients.google.com`.

**Comment by paulmach** [comment]
From what I understand the StartGroup and EndGroup are just fields, wiretype + field number, no data. They are basically parentheses. They get skipped with `.Skip()` like other types.

If you want to support them then I think you'd have to export the Data and Index fields so you can keep track of where you're at. Then do something like:
```
msg := protoscan.New(encodedData)
for msg.Next() {
    if msg.FieldNumber() == groupFieldNum && msg.WireType == WireTypeStartGroup {
        start := msg.Index
        end := msg.Index
        for msg.Next() {
             msg.Skip()
             if msg.FieldNumber() == groupFieldNum && msg.WireType == WireTypeEndGroup {
                 break
             }
             end = msg.Index
         }
         groupdata = msg.Data[start:end]
         // groupdata would be the raw protobuf encoded bytes of the fields in the group.
    }
}
```
I think that will work, of course you'd have to mix it in with all the other fields you care about.

**Comment by paulmach** [comment]
addressed as part of https://github.com/paulmach/protoscan/pull/3
